// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvgbBl5JwPLy7UoMuoJWGwAlm2hzIJf24',
    appId: '1:56342306185:web:9d1b301ef20ca668fe9558',
    messagingSenderId: '56342306185',
    projectId: 'mynotes1-ac556',
    authDomain: 'mynotes1-ac556.firebaseapp.com',
    storageBucket: 'mynotes1-ac556.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN76BduuBl2CJ8pZzjNMwnK7cw6T569Pw',
    appId: '1:56342306185:android:88b88bb7fee47dc9fe9558',
    messagingSenderId: '56342306185',
    projectId: 'mynotes1-ac556',
    storageBucket: 'mynotes1-ac556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqP47rVUCkbOIz7UHK6aQVwU7m2uJl6c',
    appId: '1:56342306185:ios:355e5cc13755e3cefe9558',
    messagingSenderId: '56342306185',
    projectId: 'mynotes1-ac556',
    storageBucket: 'mynotes1-ac556.appspot.com',
    iosClientId: '56342306185-pnjajif5306m988m9dt9v7lgc93tht3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqP47rVUCkbOIz7UHK6aQVwU7m2uJl6c',
    appId: '1:56342306185:ios:355e5cc13755e3cefe9558',
    messagingSenderId: '56342306185',
    projectId: 'mynotes1-ac556',
    storageBucket: 'mynotes1-ac556.appspot.com',
    iosClientId: '56342306185-pnjajif5306m988m9dt9v7lgc93tht3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes1',
  );
}
